# Generated by Django 6.0 on 2026-04-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_suministro_monto_alter_sst_monto_proyectado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suministro',
            name='Observación_LDS',
            field=models.TextField(blank=True, null=True),
        ),
    ]
