# Generated by Django 6.0 on 2026-04-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_suministro_observación_lds'),
    ]

    operations = [
        migrations.AddField(
            model_name='suministro',
            name='Observacion_LDS',
            field=models.TextField(blank=True, null=True),
        ),
    ]