# Generated by Django 6.0 on 2026-04-18 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_suministro_observación_lds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50, unique=True, verbose_name='Estado de Liquidación')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#007bff', help_text='Color en formato hexadecimal (#FFFFFF)', max_length=7, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Estado de Liquidación',
                'verbose_name_plural': 'Estados de Liquidación',
                'ordering': ['estado'],
            },
        ),
        migrations.AddField(
            model_name='sst',
            name='estado_liquidacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.estadoliquidacion', verbose_name='Estado de Liquidación'),
        ),
    ]
